/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atm_project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Sudhakar
 */
public class Logging_page extends javax.swing.JFrame {

    /**
     * Creates new form Main_page
     */
    public Logging_page() {
        initComponents();
           }
String name,lastname,passnum,senum;
       String driver = "com.mysql.cj.jdbc.Driver";
    Connection con = null;
    PreparedStatement pstmt = null;
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        pas = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 0, 102));
        jPanel2.setLayout(null);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("WELCOME");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 10, 90, 20);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Please enter your pin :");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(110, 110, 170, 30);

        jLabel16.setBackground(new java.awt.Color(153, 255, 255));
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/arrow-right.png"))); // NOI18N
        jPanel2.add(jLabel16);
        jLabel16.setBounds(370, 260, 20, 20);

        jLabel17.setBackground(new java.awt.Color(153, 255, 255));
        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("     Enter");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(310, 260, 60, 20);

        jLabel24.setBackground(new java.awt.Color(153, 255, 255));
        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Clear");
        jPanel2.add(jLabel24);
        jLabel24.setBounds(20, 220, 90, 20);

        jLabel25.setBackground(new java.awt.Color(153, 255, 255));
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/arrow-left.png"))); // NOI18N
        jPanel2.add(jLabel25);
        jLabel25.setBounds(0, 220, 20, 20);

        jLabel26.setBackground(new java.awt.Color(153, 255, 255));
        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Delete");
        jPanel2.add(jLabel26);
        jLabel26.setBounds(20, 260, 100, 20);

        jLabel27.setBackground(new java.awt.Color(153, 255, 255));
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/arrow-left.png"))); // NOI18N
        jPanel2.add(jLabel27);
        jLabel27.setBounds(0, 260, 20, 20);

        pas.setBackground(new java.awt.Color(0, 0, 102));
        pas.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(pas);
        pas.setBounds(150, 140, 70, 20);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(80, 60, 390, 300);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("     <");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3);
        jLabel3.setBounds(480, 320, 50, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("     <");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(480, 190, 40, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("     <");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(480, 230, 50, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("     <");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(480, 280, 50, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("     >");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 320, 40, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("     >");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8);
        jLabel8.setBounds(30, 280, 40, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("     >");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(30, 230, 40, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("    >");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(30, 190, 40, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Capture.JPG"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 550, 420);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(1, 1, 550, 420);

        setSize(new java.awt.Dimension(551, 421));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        if(pas.getText().equals(""))
        { 
        
            JOptionPane.showMessageDialog(rootPane,"Please enter password..");
            
        }
        else
        {
        
        
        
        
        String p=pas.getName();
        try{
            Class.forName(driver);
            String url = "jdbc:mysql://localhost:3306/atm";
            con =DriverManager.getConnection(url,"root","");
            pstmt = con.prepareStatement("select *from loging where pin=?");
            pstmt.setString(1,pas.getText());
           
            ResultSet rs = pstmt.executeQuery();
           
            
        if(rs.next())
        {
        
            JOptionPane.showMessageDialog(rootPane,"pin corrcet");
            
           
            String ac_info=pas.getText();
            Main_page mp=new Main_page(ac_info);
            mp.setVisible(true);
            dispose();
            
        
        }
        else
        { 
        
            JOptionPane.showMessageDialog(rootPane,"pin worng");
        
        
        
        
        }
        
            
            
      
        
        }
        catch(Exception e)
        {
            System.out.println("SQL Exception "+e);
        }
        
        
        }
        
        
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        pas.setText("");
        
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        String p=pas.getText();
        
        int ps=Integer.parseInt(p);
        int te=0;
        int t=ps%10;
        int c=te+t;
        t=ps/10;
        
        String f=String.valueOf(t);
        
        pas.setText(f);
        
        
    }//GEN-LAST:event_jLabel7MouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Logging_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Logging_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Logging_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Logging_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Logging_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField pas;
    // End of variables declaration//GEN-END:variables
}
