/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atm_project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Sudhakar
 */
public class Withdrawl extends javax.swing.JFrame {

    /**
     * Creates new form Main_page
     */
    public Withdrawl() {
        initComponents();
    }

    public Withdrawl(String msg) {
        initComponents();
        ac.setText(msg);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        ac = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        bal = new javax.swing.JLabel();
        wit = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        ac1 = new javax.swing.JLabel();
        tot = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 0, 102));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel2MouseEntered(evt);
            }
        });
        jPanel2.setLayout(null);

        ac.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(ac);
        ac.setBounds(320, 10, 60, 20);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Enter withdarwl amount :");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(70, 130, 190, 30);

        jLabel18.setBackground(new java.awt.Color(153, 255, 255));
        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Withdarwal");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(290, 260, 80, 20);

        jLabel19.setBackground(new java.awt.Color(153, 255, 255));
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/arrow-right.png"))); // NOI18N
        jPanel2.add(jLabel19);
        jLabel19.setBounds(370, 260, 20, 20);

        jLabel26.setBackground(new java.awt.Color(153, 255, 255));
        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Back");
        jPanel2.add(jLabel26);
        jLabel26.setBounds(20, 260, 100, 20);

        jLabel27.setBackground(new java.awt.Color(153, 255, 255));
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/arrow-left.png"))); // NOI18N
        jPanel2.add(jLabel27);
        jLabel27.setBounds(0, 260, 20, 20);

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("your current balance :");
        jPanel2.add(jLabel28);
        jLabel28.setBounds(80, 50, 160, 30);

        bal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bal.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(bal);
        bal.setBounds(150, 80, 160, 30);

        wit.setBackground(new java.awt.Color(0, 0, 102));
        wit.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(wit);
        wit.setBounds(170, 180, 130, 20);

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("withdrawl");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(10, 10, 100, 20);

        ac1.setForeground(new java.awt.Color(255, 255, 255));
        ac1.setText("74gtrhww");
        jPanel2.add(ac1);
        ac1.setBounds(270, 10, 60, 20);

        tot.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tot.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(tot);
        tot.setBounds(90, 220, 160, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(80, 60, 390, 300);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("     <");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3);
        jLabel3.setBounds(480, 320, 50, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("     <");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(480, 190, 40, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("     <");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(480, 230, 50, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("     <");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(480, 280, 50, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("     >");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 320, 40, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("     >");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(30, 280, 40, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("     >");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(30, 230, 40, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("    >");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(30, 190, 40, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/Capture.JPG"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 550, 420);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(1, 1, 550, 420);

        setSize(new java.awt.Dimension(551, 421));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
         String msg=ac.getText();
        
        Main_page mp=new Main_page(msg);
        
        mp.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
         if(wit.getText().equals(""))
        {
        
            JOptionPane.showMessageDialog(rootPane,"please enter amount to withdraw");
        
        }
        else{
        
        
        String baln=bal.getText();
        
        int b=Integer.parseInt(baln);
        
        String depo=wit.getText();
        
        int d=Integer.parseInt(depo);
        
        int t=b-d;
        
        String upd=String.valueOf(t);
        
        tot.setText(upd);
        
        String in=tot.getText();
           
       String driver = "com.mysql.cj.jdbc.Driver";
    Connection con = null;
    PreparedStatement pstmt1;
       
        
          try{
            Class.forName(driver);
            String url = "jdbc:mysql://localhost:3306/atm";
            con =DriverManager.getConnection(url,"root","");
            pstmt1 = con.prepareStatement("update balance set amount=? where pin=?;");
           
              pstmt1.setString(1,tot.getText());
              pstmt1.setString(2,ac.getText());
              
              pstmt1.executeUpdate();
           
              
              JOptionPane.showMessageDialog(rootPane,"Withdrawl sucessfully");
              
           
            
              
                  String msg=ac.getText();
        
        Main_page mp=new Main_page(msg);
        
        mp.setVisible(true);
        dispose();
            
           
        
            
            
           
           
           
             
           
            
        }
        catch(Exception e)
        {
            System.out.println("SQL Exception "+e);
        }
        
        }
        
        
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jPanel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseEntered
        // TODO add your handling code here:
            String info=ac.getText();
        String details[]=null;
        
       String driver = "com.mysql.cj.jdbc.Driver";
    Connection con = null;
    PreparedStatement pstmt1,pstmt2,pstmt3,pstmt4 = null;
       
        try{
            Class.forName(driver);
            String url = "jdbc:mysql://localhost:3306/atm";
            con =DriverManager.getConnection(url,"root","");
            pstmt1 = con.prepareStatement("select amount from balance where pin=?;");
           
            pstmt1.setString(1,ac.getText());
          
           
            ResultSet rs1=pstmt1.executeQuery();
           
            while(rs1.next())
            {
            
                String amount=rs1.getString("amount");
            
                bal.setText(amount);
                
             
         
            
            
            
            }
           
        
            
            
           
           
           
             
           
            
        }
        catch(Exception e)
        {
            System.out.println("SQL Exception "+e);
        }
        
    }//GEN-LAST:event_jPanel2MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Withdrawl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Withdrawl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Withdrawl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Withdrawl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Withdrawl().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ac;
    private javax.swing.JLabel ac1;
    private javax.swing.JLabel bal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel tot;
    private javax.swing.JTextField wit;
    // End of variables declaration//GEN-END:variables
}
